version: "3.0"

services:
  serviceweb:
    image: wzehren/phpsae
    ports:
      - "80:80"
    deploy:
      placement:
        constraints: [node.labels.service == web ]
      replicas: 1
    volumes:
      - "/home/pi/webVolume:/hostpipe"

  servicebd:
    image: wzehren/mysqlsae
    ports:
      - "3306:3306"
    deploy:
      placement:
        constraints: [node.labels.service == sql ]
      replicas: 1
    volumes:
      - "/var/lib/mysql_volume_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1